package mybatisMBG.bean;

public class User {
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", dId=" + dId +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.id
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.user_name
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.age
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.gender
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis.d_id
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.id
     *
     * @return the value of mybatis.id
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.id
     *
     * @param id the value for mybatis.id
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.user_name
     *
     * @return the value of mybatis.user_name
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.user_name
     *
     * @param userName the value for mybatis.user_name
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.age
     *
     * @return the value of mybatis.age
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.age
     *
     * @param age the value for mybatis.age
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.gender
     *
     * @return the value of mybatis.gender
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.gender
     *
     * @param gender the value for mybatis.gender
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis.d_id
     *
     * @return the value of mybatis.d_id
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis.d_id
     *
     * @param dId the value for mybatis.d_id
     *
     * @mbg.generated Thu Feb 20 23:26:13 CST 2020
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}